# Exemple d'utilisation du workflow de commentaire et fermeture de ticket avec version
# Ce workflow commente automatiquement les commits sur le ticket liÃ© et le ferme aprÃ¨s merge

name: ğŸ“ Commenter et clÃ´turer le ticket

on:
  pull_request:
    branches: [ develop ]
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  comment-and-close:
    name: ğŸ“ Commenter et clÃ´turer le ticket
    uses: LeZouzouEnWeb/workflows/.github/workflows/comment-and-close-ticket.yml@V1.0.5
    permissions:
      contents: read
      pull-requests: read
      issues: write


