name: ðŸ”’ VÃ©rification PR develop â†’ homol

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - homol

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-pr-source:
    name: ðŸ”’ VÃ©rification PR develop â†’ homol
    uses: LeZouzouEnWeb/workflows/.github/workflows/check-pr-source.yml@V1.0.5
    permissions:
      contents: read
      issues: write
      pull-requests: write
    with:
      source_branch: develop
      target_branch: homol
