# Exemple d'utilisation du workflow de liaison de tickets avec version
# Ce workflow dÃ©tecte et lie automatiquement les tickets/issues dans les PR

name: ðŸ”— Lier les tickets Ã  la PR

on:
  pull_request:
    branches: [ develop, homol, main ]
    types: [opened, edited, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  link-issues-in-pr:
    name: ðŸ”— Lier les tickets a la PR
    uses: LeZouzouEnWeb/workflows/.github/workflows/link-issues-in-pr.yml@V1.0.5
    permissions:
      contents: read
      pull-requests: write
